[REFACTOR/#199] clean code 적용 및 웹뷰 생성 확장함수 생성
Team-Going/Going-Android pull request #201
Opened 2024-02-13 09:55 UTC by chattymin

- closed #199 

## *⛳️ Work Description*
- clean code에서 지향하는 when(if)문 제거 완료
- openWebView 확장함수 생성 및 적용

## *📢 To Reviewers*
- when을 지우는 방법을 사용했는데 꽤 괜찮은것 같습니다
- 해당 상태에 따라 어디로 이동하는지 최 상단에 적혀있어 한눈에 찾기 편하고, 조건 탐색을 안하니 속도도 더 빨라지네요
- 물론 불필요한 객체를 만드는 것 아니냐 할 수는 있지만, 그 단점보다 속도와 가독성의 이점이 더 많은 것 같습니다
- 다른의견이 있으시면 코리 달아주시면 당연히 감사하겠구요!! 좋은 방법같으면 다들 적용시켜 보는 것을 추천드립니다

---

리뷰 받은 내용을 바탕으로 다시 많이 수정했습니다 ㅎㅎㅎ
StateFlow -> SharedFlow 작업은 제가 SharedFlow에 대해서 잘 몰라서 좀 더 공부한 후 하도록 하겠습니다!
navigateToScreenClear 확장함수도 만들었으니까 보시면 될듯듯듯

2024-02-13 12:26 UTC, Marchbreeze approved these changes
역시 넘 잘하네요 ~~~
혹시 when 문을 사용하지 않는 것을 권장하는 이유, 혹은 자료를 함께 볼 수 있을까요?

2024-02-13 12:26 UTC, Marchbreeze commented on presentation/src/main/java/com/going/presentation/designsystem/edittext/EmojiCounterEditText.kt
> +            }
굿굿~~

2024-02-13 12:26 UTC, Marchbreeze commented on presentation/src/main/java/com/going/presentation/designsystem/edittext/EmojiCounterEditText.kt
> +    )
오 이거 왕신기하네요

2024-02-13 12:26 UTC, Marchbreeze commented on presentation/src/main/java/com/going/presentation/designsystem/edittext/EmojiCounterEditText.kt
> +    )
다만 lateinit의 경우 앱이 터질 수 있을 것 같아서, 더 안정적으로 하려면 init 여부 확인하고 사용하도록 설정해두는 것도 좋을 것 같아요 ~~ (제가 로직쪽은 잘 모르니)

2024-02-13 12:26 UTC, Marchbreeze commented on presentation/src/main/java/com/going/presentation/designsystem/edittext/EmojiCounterEditText.kt
> +        binding.tvEmojiCounterEtWarningMessage.text = text
요기 바인딩들은 묶을 수도 있는 것처럼 보이네요!

2024-02-13 12:26 UTC, Marchbreeze commented on presentation/src/main/java/com/going/presentation/designsystem/edittext/EmojiCounterEditText.kt
> +        binding.tvEmojiCounterEtWarningMessage.text = text
그냥 binding 중복되는 것들을 지워주는 용도도 있지만, binding을 묶어줌에 따라서 하위 코드들은 모두 UI를 직접적으로 변경한다는 암시를 같이 줄 수도 있는 기능을 합니당~

2024-02-13 12:26 UTC, Marchbreeze commented on presentation/src/main/java/com/going/presentation/onboarding/signin/SignInActivity.kt
> +            authStateMap[state]
제가 잘 몰라서 그러는데, 자바 & 코틀린에서는 if&else를 지양하고 대신해서 when문을 사용하는 것을 권장하지 않나요..? when문 안쓰도록 설정하는건 처음 보는 것 같아요!

뭔가 저라면 when문을 안쓰더라도, authStateMap 변수 설정을 최대한 observe 내부 혹은 따로 선언하는 함수로 만들어두어서 observe 함수 근처에 배치해둘 것 같아요! 뭔가 코드 뜯어볼 때 함수보다가 다시 맨 위 변수 가서 결과 확인하고 하면서 유지보수할 때 불편할 수도 있을 것 같은 느낌쓰

2024-02-13 12:26 UTC, Marchbreeze commented on presentation/src/main/java/com/going/presentation/onboarding/splash/SplashActivity.kt
> +        private const val delayTime = 2200L
요런 상수들은 DELAY_TIME, 혹은 SPLASH_DELAY_TIME 같은 형태로 변수명 지어주면 더 변수가 아닌 상수처럼 보일 것 같습니다 !

2024-02-13 12:26 UTC, Marchbreeze commented on presentation/src/main/java/com/going/presentation/util/ActivityExt.kt
> +    }
깔꼼 ~~~

2024-02-13 12:30 UTC, Marchbreeze requested changes
when 문 관련해서 설명 듣고 싶어서 잠깐 리퀘스트로 바꿔둘게요 !

2024-02-13 13:15 UTC, chattymin commented on presentation/src/main/java/com/going/presentation/designsystem/edittext/EmojiCounterEditText.kt
> +    )
이부분에서 lateinit은 activity에서 연결해둬서 괜찮을 것 같습니다 :)
매번 새로 연결하는 이유는 같은 사유로 에러가 나더라도 나오는 에러메시지가 다르기 때문에 매번 activity에서 새로 연결해줍니다!!

2024-02-13 13:15 UTC, chattymin commented on presentation/src/main/java/com/going/presentation/designsystem/edittext/EmojiCounterEditText.kt
> +        binding.tvEmojiCounterEtWarningMessage.text = text
이건 제가 깜빡한것 같네요! 역시 디테일상호~

2024-02-13 13:19 UTC, chattymin commented on presentation/src/main/java/com/going/presentation/onboarding/splash/SplashActivity.kt
> +        private const val delayTime = 2200L
제가 깜빡했네요 허허...
해당 페이지에서 private이고, splash만 있기 때문에 그냥 DELAY_TIME으로 했습니다!

2024-02-13 13:33 UTC, leeeyubin approved these changes
역시 야무집니다!! 많은 생각해보면서 봤던 코드였어요!

2024-02-13 13:33 UTC, leeeyubin commented on presentation/src/main/java/com/going/presentation/onboarding/splash/SplashActivity.kt
> +    )
오호,, 이런 방법도 있군요!

2024-02-13 13:33 UTC, leeeyubin commented on presentation/src/main/java/com/going/presentation/onboarding/splash/SplashActivity.kt
> +        private const val delayTime = 2200L
오 변수명을 대문자로 하는 이유가 그거였군여?!!

2024-02-13 13:33 UTC, leeeyubin commented on presentation/src/main/java/com/going/presentation/setting/SettingActivity.kt
> +            openWebView(FAQ)
우와 좋아요!!

2024-02-13 14:00 UTC, chattymin commented on presentation/src/main/java/com/going/presentation/onboarding/signin/SignInActivity.kt
> +            authStateMap[state]
1. 성능적 이점 -> when 로직을 디컴파일 한 후 java로 변환하면 switch문이 나옵니다. 만약, 상단의 값이 else에 해당하는 값을 넣었을 경우 상단의 모든 경우를 전부 확인한 후 else 문이 실행됩니다. 그렇기 때문에 최악의 경우 모든 조건을 검사한 후 결과 로직을 실행하게 됩니다. 하지만, hashMap이 해싱을 사용하기 때문에 값을 탐색하는데 성능이 아주 좋기 때문에 성능이 좋아집니다. 
- 참고 링크 : https://thdev.tech/kotlin/2018/05/22/Android-Studio-Kotlin-Decompile/ 
- hashMap은 O(1)의 속도임 
- clean code 책에서 if 문을 지양하라고 나옴. -> 가독성 저하, 불필요한 비교 제거, 비즈니스 로직 분리

2. 비즈니스 로직의 분리 -> state가 변경되더라도 function 내부는 수정하지 않아도 됩니다.즉, 이후 state가 변하여 map 내부 값을 수정해도 비즈니스 로직은 수정하지 않아도 됩니다.

3. 말씀해주셨던 가독성이 오히려 상승된다고 저는 생각합니다. 해당 매핑이 최상단에 있기 때문에 해당 페이지에서 어떤 경우에 어디로 이동하는지 바로 확인이 가능하기 때문에 navigate 코드를 하나하나 찾아가지 않아도 된다는 이점이 있다고 생각합니다. 그리고 함수를 수정하고 할때 위아래로 왔다갔다를 한다기 보다는 매핑에 원하는 값을 추가하기만 하면 돼서 navigate 함수를 찾으러 다니지 않고 바로 수정이 가능하다는 장점이 크다고 생각합니다 



이 세가지가 제가 해당 로직을 구현한 이유입니다!

2024-02-13 15:47 UTC, crownjoe approved these changes
역시 갓동민 완벽하다!

2024-02-13 15:47 UTC, crownjoe commented on presentation/src/main/java/com/going/presentation/onboarding/signin/SignInActivity.kt
> +        AuthState.TENDENCY to { navigateToScreen<TendencySplashActivity>(listOf(Intent.FLAG_ACTIVITY_CLEAR_TOP)) },
분기처리 조아요 따봉!

2024-02-13 15:47 UTC, crownjoe commented on presentation/src/main/java/com/going/presentation/onboarding/splash/SplashActivity.kt
> +        }, delayTime)
const val 사용해서 쓴 것 조아욥!!!

2024-02-19 15:36 UTC, Marchbreeze approved these changes
최고최고~~~~ 좋아요

2024-02-19 15:36 UTC, Marchbreeze commented on presentation/src/main/java/com/going/presentation/onboarding/splash/SplashActivity.kt
>      }
비즈니스 로직같아보이네요! 제 스타일대로 한다면 delay까지 뷰모델에 넣어두고, 함수 실행 후 결과 값을 sharedFlow<Boolean>로 저장한 다음에, true 값이 emit되면 액티비티에서 관찰해서 navigate를 시킬 것 같아요 ~
물론 액티비티에 두어도 크게 이상하지는 않아보이고, 확장성을 고려해서 익숙한 stateFlow로 UiState같은 형태의 친구들을 활용해서 만들어도 좋구요~

2024-02-19 15:36 UTC, Marchbreeze commented on presentation/src/main/java/com/going/presentation/onboarding/splash/SplashViewModel.kt
>                      }
제가 알기론 when 문에서 else를 활용하는 게 권장되지 않는 것으로 알고 있습니다..!
물론 코드 상으로는 요게 예쁘긴 하다만 상태값들을 다 표시해두던가, 아니면
```
if (errorCode == TENDENCY) {
_userState.value = AuthState.OTHER_PAGE
return
}
_userState.value = AuthState.FAILURE
```
처럼 if-else 대신 리턴을 활용해도 괜찮을 것 같아요.
아니면 사실 그냥 코드 이쁘게 이렇게 두는것도 저는 좋음 !!

2024-02-19 15:36 UTC, Marchbreeze commented on presentation/src/main/java/com/going/presentation/tendency/result/TendencyResultActivity.kt
> +                UiState.Loading -> return@onEach
요 친구들 앞에 is 없어도 잘되나요?? 앞에 유형을 따라가는건가 신기하네

2024-02-19 15:36 UTC, Marchbreeze commented on presentation/src/main/java/com/going/presentation/designsystem/edittext/EmojiCounterEditText.kt
> +            editTextStateMap[field]?.let { setEditTextState(it) }
요 친구들은 확실히 중복되는 친구들이라 이렇게 표시해두는게 좋은 것 같네요 !! 굳굳

2024-02-19 15:43 UTC, chattymin commented on presentation/src/main/java/com/going/presentation/onboarding/splash/SplashActivity.kt
>      }
저도 viewModel로 보내야하나 고민을 많이했었는데 역시 그게 맞는 것 같네요!!
수정할게욤 ㅎㅎ

2024-02-20 08:43 UTC, chattymin commented on presentation/src/main/java/com/going/presentation/onboarding/splash/SplashViewModel.kt
>                      }
이 부분은 저도 고민을 많이 했는데 대면 회의때 말씀드리려 했습니다!
협의 후 수정하도록 하겠습니다 :)

2024-02-20 08:44 UTC, chattymin commented on presentation/src/main/java/com/going/presentation/tendency/result/TendencyResultActivity.kt
> +                UiState.Loading -> return@onEach
Empty와 Loading은 object여서 is가 없어도 됩니당~~

2024-02-21 01:16 UTC, chattymin commented on presentation/src/main/java/com/going/presentation/onboarding/splash/SplashViewModel.kt
>                      }
if문으로 수정하려했지만, 추후 확장성을 위해서 when을 유지하는게 좋을 것 같습니다!
그래서 when은 유지하되, 상태값을 전부 표시하는 방식으로 수정햇습니다 :)

2024-02-21 03:07 UTC, merged