[UI/#9] 취향 태그 뷰 / UI 구현
Team-Going/Going-Android pull request #24
Opened 2024-01-04 16:19 UTC by leeeyubin

- closed #9

## *⛳️ Work Description*
- 어댑터 구현 (List Adapter)
- Scroll View 구현
- 버튼 중복 클릭 방지 구현

## *📸 Screenshot*

https://github.com/Team-Going/Going-Android/assets/128459613/6aabc89f-b571-45d5-88e9-2a5869d7e9c9

## *📢 To Reviewers*
- 아직 디자인이 다 나오지 않아서 색상이나 폰트는 임시로 설정해뒀습니다!
- 피드백 언제나 환영입니당

2024-01-04 16:42 UTC, Marchbreeze requested changes
고생했어요~! 첫 PR인데 야무지네용 ㅎㅎ
다만 레이아웃 내에 고정값으로 박힌 크기들이 많이 보이네요 ㅜㅜ 이 친구들 수정 부탁드려욥

2024-01-04 16:42 UTC, Marchbreeze commented on app/src/main/AndroidManifest.xml
> +            android:exported="true" />
요기 다른 애들처럼 화면회전 막아주시고, pr 올릴때는 exported false로 해서 올려주셍요 ~

2024-01-04 16:42 UTC, Marchbreeze commented on build.gradle.kts
> +        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:1.8.20")
엇 요친구 없으면 안돌아가나요? 이미 들어가있는것처럼 보이는데!

2024-01-04 16:42 UTC, Marchbreeze commented on presentation/build.gradle.kts
> +    implementation("androidx.constraintlayout:constraintlayout:2.1.4")
요 친구들도 이미 들어가있어 보이는데 확인해주세요 ~

2024-01-04 16:42 UTC, Marchbreeze commented on presentation/src/main/java/com/going/presentation/preferencetag/PreferenceTagActivity.kt
> +    private val viewModel by viewModels<PreferenceTagViewModel>()
사소한거긴 한데, 저는 용도가 다른 변수들 사이에는 한줄 띄워두어용 ! 지금 보면 15,16 / 17 느낌으로?

2024-01-04 16:42 UTC, Marchbreeze commented on presentation/src/main/java/com/going/presentation/preferencetag/PreferenceTagAdapter.kt
> +    ListAdapter<PreferenceData, PreferenceTagViewHolder>(diffUtil) {
히야 굿굿 !

2024-01-04 16:42 UTC, Marchbreeze commented on presentation/src/main/java/com/going/presentation/preferencetag/PreferenceTagViewHolder.kt
> +                    }
안에 내용이 같아보이는데, when으로 구분해둔 이유가 무엇일까요?

2024-01-04 16:42 UTC, Marchbreeze commented on presentation/src/main/res/layout/activity_preference_tag.xml
> +            android:textSize="18sp"
디자인 나오면 폰트패밀리, 크기 각각 적용하지 말고 style로 사전 설정해둔거 활용해주세용 ~

2024-01-04 16:42 UTC, Marchbreeze commented on presentation/src/main/res/layout/item_preference_tag.xml
> +        android:layout_height="127dp"
요거 안됩니당 !! 레이아웃 크기는 wrap_parent, 0dp로만 만들고, 패딩과 마진 값을 적절하게 활용해서 뷰를 구현해주세요.
고정된 크기의 경우, 화면 크기가 다른 기기에서는 모든게 꺠져버려요 ~

2024-01-04 16:42 UTC, Marchbreeze commented on presentation/src/main/res/layout/item_preference_tag.xml
> +                android:layout_height="48dp"
라디오 버튼들도 크기를 고정해두면 안될 것 같아요 ! 5개를 chain을 걸어서 packed 상태로 두던가, 아니면 weight를 활용하던가 해서 반응성 있는 레이아웃으로 구현해주세요 ~

2024-01-04 16:42 UTC, Marchbreeze commented on presentation/src/main/res/values/themes.xml
> +        <item name="android:layout_height">48dp</item>
여기도 고정해두면 안될 것 같아요 ~~

2024-01-04 16:42 UTC, Marchbreeze commented on presentation/src/main/res/drawable/ic_line_black.xml
> +</vector>
선을 이미지로 활용하기 보다는, View의 색상을 검정색으로 두고 고정 height를 줘서 선처럼 보이도록 하는 방법, Material Divider를 활용하는 방법 중에 선택해서 활용하는게 더 바람직해보입니당

2024-01-04 16:42 UTC, Marchbreeze commented on presentation/src/main/res/layout/activity_preference_tag.xml
> +            android:layout_height="50dp"
여기도 wrap_content와 padding 값으로 구현해봅시다 ~
만약 내부 텍스트가 엄청 커지면 아마 잘릴거에요

2024-01-04 16:42 UTC, Marchbreeze commented on presentation/src/main/res/layout/item_preference_tag.xml
> +            android:layout_height="24dp"
여기도 고정 dp 금지 ~

2024-01-04 17:10 UTC, leeeyubin commented on build.gradle.kts
> +        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:1.8.20")
빼도 잘 돌아가네용 코끼리와 친해지기,,메모,,,

2024-01-04 17:10 UTC, leeeyubin commented on presentation/src/main/java/com/going/presentation/preferencetag/PreferenceTagActivity.kt
> +    private val viewModel by viewModels<PreferenceTagViewModel>()
사소한 피드백 좋습니다!

2024-01-04 17:49 UTC, leeeyubin commented on presentation/src/main/java/com/going/presentation/preferencetag/PreferenceTagViewHolder.kt
> +                    }
`RadioGroup`을 리스너에 연결해주는 방법을 찾다가 when문으로 각 버튼을 구분해주는 방법이 있어서 사용해보았습니당 다른 방법으로도 바꿔봤는데 확인부탁드립니당,,

2024-01-04 17:57 UTC, leeeyubin commented on presentation/src/main/res/layout/item_preference_tag.xml
> +        android:layout_height="127dp"
큰일 날 뻔했네요,, 고친다는 걸 깜빡했슴다,, 앞으로 습관화하겠습니다!!

2024-01-04 18:17 UTC, chattymin reviewed
코드 완전 잘 보고갑니다!!!
너무 잘했구 고생한게 많이 보여서 고맙네욤 ㅎㅎ

2024-01-04 18:17 UTC, chattymin commented on presentation/src/main/java/com/going/presentation/preferencetag/PreferenceTagViewHolder.kt
> +            }
group의 경우 사용하지 않는 변수기때문에 _ 로 바꾸면 좋을 것 같습니다!
아마 그렇게 하라고 가이드도 뜰거에요 :)

2024-01-04 18:17 UTC, chattymin commented on presentation/src/main/res/drawable/sel_radiobutton_text_color.xml
> +</selector>
개인적인 생각이긴 하지만 저는 checked="false" 도 써두는게 명확하게 표시할 수 있어서 좋다고 생각해요!
true일때는 이거, false일때는 저거  이렇게 표기돼있는게 더 명확하고 한눈에 볼 수 있다고 생각합니당 :)

2024-01-05 15:40 UTC, leeeyubin commented on presentation/src/main/java/com/going/presentation/preferencetag/PreferenceTagViewHolder.kt
> +            }
오호 좋은 정보 감사합니당

2024-01-05 20:21 UTC, Marchbreeze approved these changes
코리 대응 야무지게 해주셔서 감사합니닷 :)

2024-01-05 20:21 UTC, Marchbreeze commented on presentation/src/main/res/layout/item_preference_tag.xml
> +        <RadioGroup
여기 width에 chain 추후에 디자인 나온거 수정할때 꼭 걸어주세요~

2024-01-05 20:21 UTC, Marchbreeze commented on presentation/src/main/res/layout/item_preference_tag.xml
> +        <TextView
요거 그냥 view로 바꾸고 tv 대신 view_ 로 가도 될거가타용 ~

2024-01-05 20:21 UTC, Marchbreeze commented on presentation/src/main/res/layout/item_preference_tag.xml
> +            android:textColor="@color/black_000"
요친구들도 디잔대로 바꿀때 textView의 style로 적용시켜주세요~

2024-01-06 01:12 UTC, merged